# Generated by Django 3.2.8 on 2021-11-14 15:36

from django.db import migrations, models
import django_two_factor_face_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_two_factor_face_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaceimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userfaceimage',
            name='image',
            field=models.ImageField(upload_to=django_two_factor_face_auth.models.content_file_name),
        ),
    ]
