# Generated by Django 3.2.8 on 2021-11-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_two_factor_face_auth', '0005_auto_20211115_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='home_address',
        ),
    ]
