# Generated by Django 3.2.8 on 2021-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_two_factor_face_auth', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_address',
            field=models.TextField(null=True),
        ),
    ]
